/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-27 23:16:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import favorite.*;
import result.*;
import comp4321.*;
import java.util.Vector;

public final class favorite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>\r\n");
      out.write("iSearch\r\n");
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/linkList.css\" />\r\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" />-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\" />\r\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.min.css\" />-->\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/changeFavoriteStatusAndIcon.js\"></script>\r\n");
      out.write("<script src=\"js/showLinkList.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("  <link rel=\"icon\" href=\"logo.jpg\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("  <div class=\"navbar-header \r\n");
      out.write("    <a class=\"navbar-brand\"><img src=\"logo.jpg\" height=\"42\" width=\"42\"/></a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a>iSearch</a></li>\r\n");
      out.write("      <li><a href=\"index.jsp\">Search</a></li>\r\n");
      out.write("      <li><a href=\"favorite.jsp\">Favorite</a></li>\r\n");
      out.write("\t  <li><a href=\"queryHistory.jsp\">History</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"navbar-form navbar-left\" role=\"search\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\r\n");
      out.write("      <li><a><span class=\"glyphicon glyphicon-user\"></span>&nbsp;&nbsp; \r\n");
      out.write("\t  ");

		String username = "";
		if(session.isNew()){
		session.setMaxInactiveInterval(1800);
		}
		if(session.getAttribute("username")!=null)
		{
			username = (String) session.getAttribute("username");
			out.print(session.getAttribute("username"));		
		}		
		
      out.write("\t\t\r\n");
      out.write("\t  </a></li>\r\n");
      out.write("      <li><a href=\"logout.jsp\">Logout</a></li>\t  \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

Result result = new Result(null);

ChangeFavorite cf = new ChangeFavorite();
Vector<String> pageIDList = cf.getFavoriteList(username);

      out.write("\r\n");
      out.write("<p class=\"text-muted\">\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Number of Results: ");
      out.print(pageIDList.size());
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<table class=\"table table-striped\" width=90%>\r\n");

for (String i: pageIDList) {
    
      out.write("\r\n");
      out.write("    <tr><td>\r\n");
      out.write("        <div>\r\n");
      out.write("        <table border=0 bordercolor=\"#a1a1a1\" width=90% frame=void>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <div style=\"display: table-cell\">\r\n");
      out.write("        <a href=");
      out.print(result.getUrl(i));
      out.write(" target=\"_blank\"><h4>  &nbsp;&nbsp;&nbsp;\r\n");
      out.write("        ");
      out.print(result.getTitle(i));
      out.write("\r\n");
      out.write("        </h4></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"display:table-cell;whitespace:nospace;position:relative;left:10px\">\r\n");
      out.write("        <image onclick=\"changeFavoriteStatusAndIcon()\" src=\r\n");
      out.write("        ");

        ChangeFavorite changeFavorite = new ChangeFavorite();
        Vector<String> favoriteList = changeFavorite.getFavoriteList(""+ session.getAttribute("username"));
        changeFavorite.finalize();
        if(favoriteList!=null && favoriteList.contains(i))
          out.println("'favorite_on.png'");
        else
          out.println("'favorite.png'");
        
      out.write(" width=\"25px\" height=\"25px\"\r\n");
      out.write("        pageID=");
      out.print(i);
      out.write("\r\n");
      out.write("        username=");
      out.print( session.getAttribute("username"));
      out.write(" >\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"display:table-cell;whitespace:nospace;position:relative;left:20px\">\r\n");
      out.write("        </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <!-- URL row -->\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td width=70%>\r\n");
      out.write("        <a href=");
      out.print(result.getUrl(i));
      out.write(" target=\"_blank\">\r\n");
      out.write("        <h5>  &nbsp;&nbsp;&nbsp;\r\n");
      out.write("        ");
      out.print(result.getUrl(i));
      out.write("\r\n");
      out.write("        </h5></a></td>\r\n");
      out.write("        \r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td class=\"td_height\">  &nbsp;&nbsp;&nbsp; Last Modification Date:");
      out.print(result.getLastModification(i));
      out.write(" ,Size of Page:");
      out.print(result.getPageSize(i));
      out.write(" </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td class=\"td_height\">  &nbsp;&nbsp;&nbsp;\r\n");
      out.write("        ");

        Vector<WordAndFrequencyStruct> wordAndFrequencyList = result.getTopWordList(i);
        String similarPageQuery = "";
        for(WordAndFrequencyStruct wf : wordAndFrequencyList)
        {
            similarPageQuery += (" " + wf.wordString);
        }
        if(similarPageQuery != null && similarPageQuery.length() >0)
        {similarPageQuery = similarPageQuery.substring(1);}
        
      out.write("\r\n");
      out.write("        ");

        for(WordAndFrequencyStruct wf : wordAndFrequencyList)
        {
            out.println(wf.wordString + ",");
            out.println(wf.frequency + " ");
        }
        
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td class=\"td_height\">  &nbsp;&nbsp;&nbsp;\r\n");
      out.write("        <button class=\"btn btn-default\" onclick=");
      out.print("showLinkList('parent"+i+"')");
      out.write(" >Parent Links</button>\r\n");
      out.write("        &nbsp;\r\n");
      out.write("        <button class=\"btn btn-default\" onclick=");
      out.print("showLinkList('child"+i+"')");
      out.write(" ><font color='blue'>Child Links</font></button>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"position:relative;top:3px\" class=\"hidden_menu\" id=");
      out.print("parent"+i);
      out.write(" >\r\n");
      out.write("        <ul>\r\n");
      out.write("        ");

        Vector<String> parentLinkList = result.getParentLinks(i);
        for(String parentLink : parentLinkList)
        {
            out.println("<li>" + parentLink+"</li>");
        }
        
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"position:relative;top:3px\" class=\"hidden_menu\" id=");
      out.print("child"+i);
      out.write(" >\r\n");
      out.write("        <ul>\r\n");
      out.write("        ");

        Vector<String> childLinkList = result.getChildLinks(i);
        for(String childLink : childLinkList)
        {
            out.println("<li><font color='blue'>" + childLink+"</font></li>");
        }
        
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
