/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-27 22:34:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html><html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>\r\n");
      out.write("iSearch\r\n");
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/linkList.css\" />\r\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" />-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\" />\r\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.min.css\" />-->\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#letterpress {\r\n");
      out.write("\tmargin-top:10%;\r\n");
      out.write("\ttext-align://center;\r\n");
      out.write("}\r\n");
      out.write("body\r\n");
      out.write("{ \r\n");
      out.write("background-image:url('colortree.jpg');\r\n");
      out.write("background-repeat:no-repeat;\r\n");
      out.write("background-attachment:fixed;\r\n");
      out.write("background-position:right bottom; \r\n");
      out.write("background-size:400px 400px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/findWords.js\"></script>\r\n");
      out.write("  <link rel=\"icon\" href=\"logo.jpg\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"test()\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("  <div class=\"navbar-header \r\n");
      out.write("    <a class=\"navbar-brand\"><img src=\"logo.jpg\" height=\"42\" width=\"42\"/></a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a>iSearch</a></li>\r\n");
      out.write("      <li><a href=\"index.jsp\">Search</a></li>\r\n");
      out.write("      <li><a href=\"favorite.jsp\">Favorite</a></li>\r\n");
      out.write("\t  <li><a href=\"queryHistory.jsp\">History</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"navbar-form navbar-left\" role=\"search\">\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\r\n");
      out.write("      <li><a><span class=\"glyphicon glyphicon-user\"></span>&nbsp;&nbsp; \r\n");
      out.write("\t  ");

		if(session.isNew()){
		session.setMaxInactiveInterval(1800);
		}else{
			if(session.getAttribute("username")!=null)
			{
				out.print(session.getAttribute("username"));		
			}
			
		}
		
      out.write("\t\t\r\n");
      out.write("\t  </a></li>\r\n");
      out.write("      <li><a href=\"logout.jsp\">Logout</a></li>\t  \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\" id=\"letterpress\"><img src=\"iSearch.png\"/></div>\r\n");
      out.write("</br>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<form class=\"form-inline\" method=\"post\" action=\"query.jsp\">\r\n");
      out.write("     <div class=\"form-group\" style=\"width:30%\">\r\n");
      out.write("         <input onkeyup=\"findWords()\" onblur=\"clearWords()\"  id=\"textField\" type=\"text\" style=\"font-size:15px\" name=\"txtname\" class=\"form-control\" placeholder=\"Enter query\" autocomplete=\"off\"></div>\r\n");
      out.write("\t<input type=\"submit\" value=\"Search\" class=\"btn btn-default\">\r\n");
      out.write("</form>\r\n");
      out.write("<div style=\"position:relative;left:13px;text-align:left\">\r\n");
      out.write("<!--<ul >-->\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td id=\"spacer\" style=\"visibility:hidden;font-size:15px;\"></td>\r\n");
      out.write("<td id=\"list8\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"position:absolute;left:31%;top:2px\">\r\n");
      out.write("<ul class=\"nav nav-pills\" id=\"testLabel\" >\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
