/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-27 22:34:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import favorite.*;
import result.*;
import comp4321.*;
import java.util.Vector;

public final class query_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>\n");
      out.write("iSearch\n");
      out.write("</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/linkList.css\" />\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" />-->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\" />\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.min.css\" />-->\n");
      out.write("\n");
      out.write("<script src=\"js/changeFavoriteStatusAndIcon.js\"></script>\n");
      out.write("<script src=\"js/showLinkList.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("  <link rel=\"icon\" href=\"logo.jpg\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-default\" role=\"navigation\">\n");
      out.write("  <div class=\"navbar-header \n");
      out.write("    <a class=\"navbar-brand\"><img src=\"logo.jpg\" height=\"42\" width=\"42\"/></a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div>\n");
      out.write("    <ul class=\"nav navbar-nav\">\n");
      out.write("      <li class=\"active\"><a>iSearch</a></li>\n");
      out.write("      <li><a href=\"index.jsp\">Search</a></li>\n");
      out.write("      <li><a href=\"favorite.jsp\">Favorite</a></li>\n");
      out.write("\t  <li><a href=\"queryHistory.jsp\">History</a></li>\n");
      out.write("    </ul>\n");
      out.write("    <form class=\"navbar-form navbar-left\" role=\"search\">\n");
      out.write("    </form> \n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\n");
      out.write("      <li><a><span class=\"glyphicon glyphicon-user\"></span>&nbsp;&nbsp; \n");
      out.write("\t  ");

		if(session.isNew()){
		session.setMaxInactiveInterval(1800);
		}
		
		if(session.getAttribute("username")!=null)
		{
			out.print(session.getAttribute("username"));		
		}

		
      out.write("\t\t\n");
      out.write("\t  </a></li>\n");
      out.write("      <li><a href=\"logout.jsp\">Logout</a></li>\t  \n");
      out.write("    </ul>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");


Result result = new Result(null);
Vector<Score> pageIDList = new Vector<Score>();
String query = "";
ResultInfo info = new ResultInfo("",0,0);
if(request.getParameter("txtname")!=null)
{
	//out.println("You input "+request.getParameter("txtname"));
    query = request.getParameter("txtname");
	Query q = new Query();
	pageIDList = q.getScore( ((String) session.getAttribute("username")), query, info);
}
else
{
	//out.println("You input nothing");
}


      out.write("\n");
      out.write("\n");
      out.write("<form class=\"form-inline\" role=\"form\" method=\"post\" action=\"query.jsp\" style=\"position:relative;top:10;left:50\">\n");
      out.write("<img height=\"46\" width=\"140\" src=\"iSearch.png\"/>&nbsp;&nbsp;&nbsp;\n");
      out.write("<div class=\"form-group\">\n");
      out.write("<input style=\"width:550;height:50;font-size:18px\" type=\"text\" class=\"form-control\" name=\"txtname\" placeholder=\"Enter query\" value=");
      out.print("'"+query+"'" );
      out.write(" >\n");
      out.write("</div>\n");
      out.write("<input style=\"width:100;height:50;font-size:18px\" type=\"submit\" value=\"Search\" class=\"btn btn-primary\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<div style=\"position:relative;top:15\">\n");
      out.write("<div style=\"position:relative;left:50\">\n");
      out.write("<p class=\"text-muted\">\n");
      out.write("Total time: ");
      out.print(info.time);
      out.write("\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Number of Results: ");
      out.print(info.numberOfResult);
      out.write(" (only top 50 results are showed)</p>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<table class=\"table table-striped\" width=90%>\n");

for (Score i: pageIDList) {

    
      out.write("\n");
      out.write("    <tr><td>\n");
      out.write("        <div >\n");
      out.write("        <table border=0 bordercolor=\"#a1a1a1\" width=90% frame=void>\n");
      out.write("        <tr>\n");
      out.write("        <td rowspan=\"5\" width=10% align=\"middle\">\n");
      out.write("        ");
 out.println(i.overall + "</br>");
            out. println("VS_B:" + i.vsScoreBody + "</br>");
			out. println("VS_T:" + i.vsScoreTitle + "</br>");
            out. println("PR:" + i.pageRank);
      out.write("</td>\n");
      out.write("        \n");
      out.write("        <td width=60%>\n");
      out.write("        <div style=\"display: table-cell\">\n");
      out.write("        <a href=");
      out.print(result.getUrl(i.page_id));
      out.write(" target=\"_blank\"><h4>\n");
      out.write("        ");
      out.print(result.getTitle(i.page_id));
      out.write("\n");
      out.write("        </h4></a>\n");
      out.write("        </div>\n");
      out.write("        <div style=\"display:table-cell;whitespace:nospace;position:relative;left:10px\">\n");
      out.write("        <image onclick=\"changeFavoriteStatusAndIcon()\" src=\n");
      out.write("        ");

        ChangeFavorite changeFavorite = new ChangeFavorite();
        Vector<String> favoriteList = changeFavorite.getFavoriteList(""+ session.getAttribute("username"));
        changeFavorite.finalize();
        if(favoriteList!=null && favoriteList.contains(i.page_id))
          out.println("'favorite_on.png'");
        else
          out.println("'favorite.png'");
        
      out.write(" width=\"25px\" height=\"25px\"\n");
      out.write("        pageID=");
      out.print(i.page_id);
      out.write("\n");
      out.write("        username=");
      out.print( session.getAttribute("username"));
      out.write(" >\n");
      out.write("        </div>\n");
      out.write("        <div style=\"display:table-cell;whitespace:nospace;position:relative;left:20px\">\n");
      out.write("        </div>\n");
      out.write("        </td>\n");
      out.write("        </tr>\n");
      out.write("        \n");
      out.write("        <!-- URL row -->\n");
      out.write("        <tr>\n");
      out.write("        <td width=70%>\n");
      out.write("        <a href=");
      out.print(result.getUrl(i.page_id));
      out.write(" target=\"_blank\">\n");
      out.write("        <h5>\n");
      out.write("        ");
      out.print(result.getUrl(i.page_id));
      out.write("\n");
      out.write("        </h5></a></td>\n");
      out.write("        \n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        <td class=\"td_height\">Last Modification Date:");
      out.print(result.getLastModification(i.page_id));
      out.write(" ,Size of Page:");
      out.print(result.getPageSize(i.page_id));
      out.write(" </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        <td class=\"td_height\">\n");
      out.write("        ");

        Vector<WordAndFrequencyStruct> wordAndFrequencyList = result.getTopWordList(i.page_id);
        String similarPageQuery = "";
        for(WordAndFrequencyStruct wf : wordAndFrequencyList)
        {
            similarPageQuery += (" " + wf.wordString);
        }
        if(similarPageQuery != null && similarPageQuery.length() >0)
        {similarPageQuery = similarPageQuery.substring(1);}
        
      out.write("\n");
      out.write("        ");

        for(WordAndFrequencyStruct wf : wordAndFrequencyList)
        {
            out.println(wf.wordString + ",");
            out.println(wf.frequency + " ");
        }
        
      out.write("\n");
      out.write("        </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("        <td class=\"td_height\">\n");
      out.write("        <button class=\"btn btn-default\" onclick=");
      out.print("showLinkList('parent"+i.page_id+"')");
      out.write(" >Parent Links</button>\n");
      out.write("        &nbsp;\n");
      out.write("        <button class=\"btn btn-default\" onclick=");
      out.print("showLinkList('child"+i.page_id+"')");
      out.write(" ><font color='blue'>Child Links</font></button>\n");
      out.write("        &nbsp;\n");
      out.write("        <form style=\"display:inline\" action=\"query.jsp\">\n");
      out.write("        <button type=\"submit\" class=\"btn btn-default\">Similar Pages</button>\n");
      out.write("        <input type=\"hidden\" name=\"txtname\" value = ");
      out.print("'"+similarPageQuery+"'");
      out.write(" >\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <div style=\"position:relative;top:3px\" class=\"hidden_menu\" id=");
      out.print("parent"+i.page_id);
      out.write(" >\n");
      out.write("        <ul>\n");
      out.write("        ");

        Vector<String> parentLinkList = result.getParentLinks(i.page_id);
        for(String parentLink : parentLinkList)
        {
            out.println("<li>" + parentLink+"</li>");
        }
        
      out.write("\n");
      out.write("        </ul>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div style=\"position:relative;top:3px\" class=\"hidden_menu\" id=");
      out.print("child"+i.page_id);
      out.write(" >\n");
      out.write("        <ul>\n");
      out.write("        ");

        Vector<String> childLinkList = result.getChildLinks(i.page_id);
        for(String childLink : childLinkList)
        {
            out.println("<li><font color='blue'>" + childLink+"</font></li>");
        }
        
      out.write("\n");
      out.write("        </ul>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        </td>\n");
      out.write("        </tr>\n");
      out.write("        \n");
      out.write("        </table>\n");
      out.write("        </div>\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("    ");

}

      out.write("\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
