/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-08-27 23:16:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import favorite.*;
import result.*;
import comp4321.*;
import java.util.Vector;

public final class queryHistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>\n");
      out.write("iSearch\n");
      out.write("</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/linkList.css\" />\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" />-->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.css\" />\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-theme.min.css\" />-->\n");
      out.write("\n");
      out.write("<script src=\"js/changeFavoriteStatusAndIcon.js\"></script>\n");
      out.write("<script src=\"js/showLinkList.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("  <link rel=\"icon\" href=\"logo.jpg\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-default\" role=\"navigation\">\n");
      out.write("<div class=\"navbar-header\n");
      out.write("<a class=\"navbar-brand\"><img src=\"logo.jpg\" height=\"42\" width=\"42\"/></a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<ul class=\"nav navbar-nav\">\n");
      out.write("<li class=\"active\"><a>iSearch</a></li>\n");
      out.write("<li><a href=\"index.jsp\">Search</a></li>\n");
      out.write("<li><a href=\"favorite.jsp\">Favorite</a></li>\n");
      out.write("<li><a href=\"queryHistory.jsp\">History</a></li>\n");
      out.write("</ul>\n");
      out.write("<form class=\"navbar-form navbar-left\" role=\"search\">\n");
      out.write("</form>\n");
      out.write("<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\n");
      out.write("<li><a><span class=\"glyphicon glyphicon-user\"></span>&nbsp;&nbsp;\n");

String username = "";
if(session.isNew()){
    session.setMaxInactiveInterval(1800);
}
if(session.getAttribute("username")!=null)
{
    username = (String) session.getAttribute("username");
    out.print(session.getAttribute("username"));
}

      out.write("\n");
      out.write("</a></li>\n");
      out.write("<li><a href=\"logout.jsp\">Logout</a></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("</nav>\n");
      out.write("\n");

Result result = new Result(null);


      out.write("\n");
      out.write("\n");
      out.write("<div style=\"position:relative;top:15\">\n");
      out.write("<table class=\"table table-striped\" width=90%>\n");
      out.write("<tr>\n");
      out.write("<th style=\"text-align:center\">&nbsp;#</th>\n");
      out.write("<th>Query</th>\n");
      out.write("<th>Time Comsumed</th>\n");
      out.write("<th># of results</th>\n");
      out.write("</tr>\n");


QueryHistory queryHistory = new QueryHistory();
Vector<ResultInfo> queryList = queryHistory.getQueryList(username);
int num = 0;
for (ResultInfo info: queryList) {
    
      out.write("\n");
      out.write("    <tr>\n");
      out.write("    <td style=\"text-align:center\">&nbsp;");
      out.print(++num);
      out.write("</td>\n");
      out.write("    <td>\n");
      out.write("    <div>\n");
      out.write("    <h4><a href=");
      out.print( "\"query.jsp?txtname=" + info.query.replaceAll("\"", "'") + "\"");
      out.write(" >\n");
      out.write("    ");

    out.println(info.query);

    
      out.write("\n");
      out.write("    </a>\n");
      out.write("    </h4>\n");
      out.write("    </div>\n");
      out.write("    </td>\n");
      out.write("    <td>\n");
      out.write("    ");
      out.print(info.time);
      out.write("\n");
      out.write("    </td>\n");
      out.write("    <td>\n");
      out.write("    ");
      out.print(info.numberOfResult);
      out.write("\n");
      out.write("    </td>\n");
      out.write("    </tr>\n");
      out.write("    ");

}

      out.write("\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
